language: python
python:
  - "2.7"
install:
 - pip install slate
 - pip install pdfminer
 - pip install -q Django --use-mirrors
 - pip install -q -e . --use-mirrors
before_install:
 - cp django_pdf/tests/settings.py .
script:
 - django-admin.py test django_pdf --settings=settings
